=== Henrique-Henrique/Hengo/addons/hengo/assets/data/script_data_schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"connections": {
			"type": "array",
			"items": {
				"$ref": "#/$defs/connection"
			}
		},
		"deps": {
			"type": "array"
		},
		"flow_connections": {
			"type": "array",
			"items": {
				"$ref": "#/$defs/connection"
			}
		},
		"node_counter": {
			"type": "integer",
			"minimum": 0
		},
		"path": {
			"type": "string",
			"pattern": "^res://.*"
		},
		"side_bar_list": {
			"type": "object",
			"properties": {
				"func_list": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/functionDefinition"
					}
				},
				"macro_list": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/macroDefinition"
					}
				},
				"signal_callback_list": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/signalCallbackDefinition"
					}
				},
				"var_list": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/variable"
					}
				},
				"signal_list": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/signalDefinition"
					}
				}
			},
			"required": [
				"func_list",
				"macro_list",
				"signal_callback_list",
				"var_list",
				"signal_list"
			]
		},
		"state_event_list": {
			"type": "array"
		},
		"type": {
			"type": "string"
		},
		"virtual_cnode_list": {
			"type": "array",
			"items": {
				"$ref": "#/$defs/virtualCNode"
			}
		}
	},
	"required": [
		"connections",
		"deps",
		"flow_connections",
		"node_counter",
		"path",
		"side_bar_list",
		"state_event_list",
		"type",
		"virtual_cnode_list"
	],
	"$defs": {
		"connection": {
			"type": "object",
			"properties": {
				"from_id": {
					"type": "integer"
				},
				"from_vc_id": {
					"type": "integer"
				},
				"to_id": {
					"type": "integer"
				},
				"to_vc_id": {
					"type": "integer"
				}
			},
			"required": [
				"from_id",
				"from_vc_id",
				"to_id",
				"to_vc_id"
			]
		},
		"ioParameter": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer"
				},
				"name": {
					"type": "string"
				},
				"type": {
					"type": "string"
				},
				"ref_id": {
					"type": "integer"
				},
				"category": {
					"type": "string"
				},
				"code_value": {
					"type": "string"
				},
				"value": {
					"type": "any"
				},
				"is_ref": {
					"type": "boolean"
				}
			},
			"required": [
				"id",
				"name"
			]
		},
		"ioBaseParameter": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer"
				},
				"name": {
					"type": "string"
				},
				"type": {
					"type": "string"
				}
			},
			"required": [
				"id",
				"name"
			]
		},
		"variable": {
			"type": "object",
			"properties": {
				"export": {
					"type": "boolean"
				},
				"id": {
					"type": "integer"
				},
				"name": {
					"type": "string"
				},
				"type": {
					"type": "string"
				}
			},
			"required": [
				"export",
				"id",
				"name",
				"type"
			]
		},
		"virtualCNode": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer"
				},
				"name": {
					"type": "string"
				},
				"position": {
					"type": "string",
					"pattern": "^Vector2\\(\\s*-?\\d+(\\.\\d+)?\\s*,\\s*-?\\d+(\\.\\d+)?\\s*\\)$"
				},
				"size": {
					"type": "string",
					"pattern": "^Vector2\\(\\s*-?\\d+(\\.\\d+)?\\s*,\\s*-?\\d+(\\.\\d+)?\\s*\\)$"
				},
				"sub_type": {
					"type": "integer"
				},
				"type": {
					"type": "integer"
				},
				"can_delete": {
					"type": "boolean"
				},
				"inputs": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioParameter"
					}
				},
				"outputs": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioParameter"
					}
				},
				"ref_id": {
					"type": "integer"
				},
				"category": {
					"type": "string"
				},
				"to_flow": {
					"type": "array"
				},
				"virtual_cnode_list": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/virtualCNode"
					}
				}
			},
			"required": [
				"id",
				"name",
				"position",
				"size",
				"sub_type",
				"type"
			]
		},
		"functionDefinition": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer"
				},
				"name": {
					"type": "string"
				},
				"inputs": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioParameter"
					}
				},
				"outputs": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioParameter"
					}
				},
				"local_vars": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/variable"
					}
				},
				"virtual_cnode_list": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/virtualCNode"
					}
				}
			},
			"required": [
				"id",
				"name",
				"inputs",
				"outputs",
				"local_vars",
				"virtual_cnode_list"
			]
		},
		"macroDefinition": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer"
				},
				"name": {
					"type": "string"
				},
				"inputs": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioParameter"
					}
				},
				"inputs_value": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioParameter"
					}
				},
				"outputs": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioParameter"
					}
				},
				"outputs_value": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioParameter"
					}
				},
				"local_vars": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/variable"
					}
				},
				"virtual_cnode_list": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/virtualCNode"
					}
				}
			},
			"required": [
				"id",
				"name",
				"inputs",
				"inputs_value",
				"outputs",
				"outputs_value",
				"local_vars",
				"virtual_cnode_list"
			]
		},
		"signalCallbackDefinition": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer"
				},
				"name": {
					"type": "string"
				},
				"bind_params": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioParameter"
					}
				},
				"params": {
					"type": "array"
				},
				"local_vars": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/variable"
					}
				},
				"signal_name": {
					"type": "string"
				},
				"signal_name_to_code": {
					"type": "string"
				},
				"type": {
					"type": "string"
				},
				"virtual_cnode_list": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/virtualCNode"
					}
				}
			},
			"required": [
				"id",
				"name",
				"bind_params",
				"params",
				"local_vars",
				"signal_name",
				"signal_name_to_code",
				"type",
				"virtual_cnode_list"
			]
		},
		"signalDefinition": {
			"type": "object",
			"properties": {
				"id": {
					"type": "integer"
				},
				"name": {
					"type": "string"
				},
				"inputs": {
					"type": "array",
					"items": {
						"$ref": "#/$defs/ioBaseParameter"
					}
				}
			},
			"required": [
				"id",
				"name",
				"inputs"
			]
		}
	}
}

=== Henrique-Henrique/Hengo/tests/assets/script_data_complete.json
{
	"connections": [
		{
			"from_id": 31,
			"from_vc_id": 29,
			"to_id": 28,
			"to_vc_id": 27
		}
	],
	"deps": [],
	"flow_connections": [
		{
			"from_id": 0,
			"from_vc_id": 1,
			"to_id": 0,
			"to_vc_id": 2
		},
		{
			"from_id": 0,
			"from_vc_id": 3,
			"to_id": 0,
			"to_vc_id": 27
		}
	],
	"node_counter": 32,
	"path": "res://hengo/new.gd",
	"side_bar_list": {
		"func_list": [
			{
				"id": 6,
				"inputs": [
					{
						"id": 11,
						"name": "name 0",
						"type": "Variant"
					}
				],
				"local_vars": [
					{
						"export": false,
						"id": 32,
						"name": "var 158637408",
						"type": "Variant"
					}
				],
				"name": "func 82104304",
				"outputs": [
					{
						"id": 13,
						"name": "name 0",
						"type": "Variant"
					}
				],
				"virtual_cnode_list": [
					{
						"can_delete": false,
						"id": 8,
						"inputs": [
							{
								"id": 14,
								"name": "name 0",
								"ref_id": 13,
								"type": "Variant"
							}
						],
						"name": "output",
						"position": "Vector2(400, 0)",
						"ref_id": 6,
						"size": "Vector2(149, 82)",
						"sub_type": 19,
						"type": 0
					}
				]
			}
		],
		"macro_list": [
			{
				"id": 17,
				"inputs": [
					{
						"id": 20,
						"name": "HenTypeFlow 0"
					}
				],
				"inputs_value": [
					{
						"id": 22,
						"name": "name 0",
						"type": "Variant"
					}
				],
				"local_vars": [],
				"name": "macro 92142483",
				"outputs": [
					{
						"id": 21,
						"name": "HenTypeFlow 0"
					}
				],
				"outputs_value": [
					{
						"id": 24,
						"name": "name 0",
						"type": "Variant"
					}
				],
				"virtual_cnode_list": [
					{
						"can_delete": false,
						"id": 18,
						"name": "input",
						"outputs": [
							{
								"id": 22,
								"name": "name 0",
								"ref_id": 22,
								"type": "Variant"
							}
						],
						"position": "Vector2(0, 0)",
						"ref_id": 17,
						"size": "Vector2(0, 0)",
						"sub_type": 43,
						"type": 9
					},
					{
						"can_delete": false,
						"id": 19,
						"inputs": [
							{
								"id": 24,
								"name": "name 0",
								"ref_id": 24,
								"type": "Variant"
							}
						],
						"name": "output",
						"position": "Vector2(400, 0)",
						"ref_id": 17,
						"size": "Vector2(0, 0)",
						"sub_type": 44,
						"type": 10
					}
				]
			}
		],
		"signal_callback_list": [
			{
				"bind_params": [
					{
						"id": 15,
						"name": "a",
						"type": "Variant"
					}
				],
				"id": 9,
				"local_vars": [],
				"name": "signal 84037735",
				"params": [],
				"signal_name": "",
				"signal_name_to_code": "",
				"type": "Variant",
				"virtual_cnode_list": [
					{
						"can_delete": false,
						"id": 10,
						"name": "signal",
						"outputs": [
							{
								"id": 16,
								"name": "a",
								"ref_id": 15,
								"type": "Variant"
							}
						],
						"position": "Vector2(0, 0)",
						"ref_id": 9,
						"size": "Vector2(0, 0)",
						"sub_type": 39,
						"type": 0
					}
				]
			}
		],
		"var_list": [
			{
				"export": false,
				"id": 26,
				"name": "var 96741951",
				"type": "Variant"
			}
		],
		"signal_list": [
			{
				"id": 26,
				"name": "new name",
				"inputs": [
					{
						"id": 12,
						"name": "name 5",
						"type": "Node"
					},
					{
						"id": 11,
						"name": "name 2",
						"type": "Node"
					}
				]
			}
		]
	},
	"state_event_list": [],
	"type": "Node",
	"virtual_cnode_list": [
		{
			"can_delete": false,
			"id": 1,
			"name": "Stat State",
			"position": "Vector2(0, 0)",
			"size": "Vector2(92, 61)",
			"sub_type": 37,
			"type": 6
		},
		{
			"id": 2,
			"name": "State 1",
			"position": "Vector2(166.744, 223.521)",
			"size": "Vector2(71, 42)",
			"sub_type": 36,
			"to_flow": [],
			"type": 5,
			"virtual_cnode_list": [
				{
					"can_delete": false,
					"id": 3,
					"name": "enter",
					"position": "Vector2(0, 0)",
					"size": "Vector2(60, 42)",
					"sub_type": 10,
					"type": 0
				},
				{
					"can_delete": false,
					"id": 4,
					"name": "update",
					"outputs": [
						{
							"id": 5,
							"name": "delta",
							"type": "float"
						}
					],
					"position": "Vector2(400, 0)",
					"size": "Vector2(102, 82)",
					"sub_type": 10,
					"type": 0
				},
				{
					"category": "native",
					"id": 27,
					"inputs": [
						{
							"category": "default_value",
							"code_value": "null",
							"id": 28,
							"name": "content",
							"type": "Variant",
							"value": "null"
						}
					],
					"name": "print",
					"position": "Vector2(-50.3268, 215.28)",
					"size": "Vector2(120, 82)",
					"sub_type": 1,
					"type": 0
				},
				{
					"id": 29,
					"inputs": [
						{
							"category": "default_value",
							"code_value": "_ref.",
							"id": 30,
							"is_ref": true,
							"name": "Node",
							"type": "Node"
						}
					],
					"name": "is_inside_tree",
					"outputs": [
						{
							"id": 31,
							"name": "",
							"type": "bool"
						}
					],
					"position": "Vector2(-374.625, 284.308)",
					"size": "Vector2(184, 82)",
					"sub_type": 0,
					"type": 0
				}
			]
		}
	]
}
